//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by filter_pack.rc
//
#define IDR_MAINFRAME                   1
#define IDS_PRODUCT_AUTHOR              10
#define IDS_PRODUCT_DESCRIPTION         11
#define IDS_FILTER_GENRE_TONE           30
#define IDS_FILTER_GENRE_ALLAXIS        31
#define IDS_FILTER_GENRE_OPAQUE         32
#define IDS_FILTER_GENRE_GLASS          33
#define IDS_FILTER_GENRE_SPECIAL        34
#define IDS_FILTER_NAME_INVERSE         50
#define IDS_FILTER_NAME_SEPIA           51
#define IDS_FILTER_NAME_SOLARIZATION    52
#define IDS_FILTER_NAME_POSTERIZATION   53
#define IDS_FILTER_NAME_RIPPLE          54
#define IDS_FILTER_NAME_WRENCH          55
#define IDS_FILTER_NAME_OPAQUE          56
#define IDS_FILTER_NAME_SHARPEN         57
#define IDS_FILTER_NAME_GLASSTILE       58
#define IDS_FILTER_NAME_MOSAIC          59
#define IDD_OPTION_SEPIA                100
#define IDD_OPTION_SOLARIZATION         101
#define IDD_OPTION_POSTERIZATION        102
#define IDD_OPTION_RIPPLE               200
#define IDD_OPTION_WRENCH               201
#define IDD_OPTION_GLASSTILE            300
#define IDC_OPTION_SEPIA_SLIDER_STRENGTH 1001
#define IDC_OPTION_SEPIA_STATIC_PREVIEW 1002
#define IDC_OPTION_SOLARIZATION_SCROLL_THRESHOLD 1100
#define IDC_OPTION_SOLARIZATION_STATIC_THRESHOLD 1101
#define IDC_OPTION_SOLARIZATION_CHANNEL_RED 1102
#define IDC_OPTION_SOLARIZATION_CHANNEL_GREEN 1103
#define IDC_OPTION_SOLARIZATION_CHANNEL_BLUE 1104
#define IDC_OPTION_SOLARIZATION_STATIC_PREVIEW 1105
#define IDC_OPTION_POSTERIZATION_SCROLL_TONE 1200
#define IDC_OPTION_POSTERIZATION_STATIC_TONE 1201
#define IDC_OPTION_POSTERIZATION_STATIC_PREVIEW 1202
#define IDC_OPTION_RIPPLE_SCROLL_CENTER_X 2000
#define IDC_OPTION_RIPPLE_STATIC_CENTER_X 2001
#define IDC_OPTION_RIPPLE_SCROLL_CENTER_Y 2002
#define IDC_OPTION_RIPPLE_STATIC_CENTER_Y 2003
#define IDC_OPTION_RIPPLE_SCROLL_AMPLITUDE 2004
#define IDC_OPTION_RIPPLE_STATIC_AMPLITUDE 2005
#define IDC_OPTION_RIPPLE_SCROLL_CYCLE  2006
#define IDC_OPTION_RIPPLE_STATIC_CYCLE  2007
#define IDC_OPTION_RIPPLE_SCROLL_PHASE  2008
#define IDC_OPTION_RIPPLE_STATIC_PHASE  2009
#define IDC_OPTION_RIPPLE_SCROLL_DISTANCE 2010
#define IDC_OPTION_RIPPLE_STATIC_DISTANCE 2011
#define IDC_OPTION_RIPPLE_STATIC_PREVIEW 2012
#define IDC_OPTION_WRENCH_SCROLL_X      2100
#define IDC_OPTION_WRENCH_STATIC_X      2101
#define IDC_OPTION_WRENCH_SCROLL_Y      2102
#define IDC_OPTION_WRENCH_STATIC_Y      2103
#define IDC_OPTION_WRENCH_SCROLL_RADIUS 2104
#define IDC_OPTION_WRENCH_STATIC_RADIUS 2105
#define IDC_OPTION_WRENCH_SCROLL_ANGLE  2106
#define IDC_OPTION_WRENCH_STATIC_ANGLE  2107
#define IDC_OPTION_WRENCH_STATIC_PREVIEW 2108
#define IDC_OPTION_GLASSTILE_EDIT_WIDTH 3000
#define IDC_OPTION_GLASSTILE_SPIN_WIDTH 3001
#define IDC_OPTION_GLASSTILE_EDIT_HEIGHT 3002
#define IDC_OPTION_GLASSTILE_SPIN_HEIGHT 3003
#define IDC_OPTION_GLASSTILE_STATIC_PREVIEW 3004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
